on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.0
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.1
          token: ${{ secrets.TOKEN }}






# push to master, main, develop
# pull request on main master
